### ISSUE TITLE
Sometimes wrong Calculation for quests < level 10 or maybe not?!

### ISSUE THREAD

**Issue by fubaWoW** [MrFox42/libquestxp#1]
hi there,

i figured out that some low level quest (< level 10) **can** return a wrong value.

for Example...  
Quest: [The Hunt Begins](https://classic.wowhead.com/quest=747/the-hunt-begins)  
Character Level: 12  
Formula `GetAdjustedXP` return: 15  
Wowhead Say: 20  

If the my Character is Level 12 (lowest experience gain for that quest) your formula `GetAdjustedXP` returns the value 15.  
WowHead on the other side says the Value should be 20.  

This **only** happens on low level qeusts **and also** not for all of them!  

I've also found an artice for [Experience point @ https://wow.gamepedia.com](https://wow.gamepedia.com/Experience_point)  
where they say:  
```
Some lower level quests (Quest_Level < 10) seem to give full XP only for Character_Level <= Quest_Level + 4, differing by 1 level with the table above.
```

so this is at first not really a big problem and second i dont really figured out how to find out what quest exactly is affected by this.

OR maybe Wowhead do wrong calculation but i dont think so.

I just thought i will inform you about this or maybe you already know this.

Anyway -> Very Nice LIB!

**Comment by MrFox42** [comment]
Hi,

First of all, sorry, I somehow missed the notification to this issue.

Wowhead sometimes has the wrong calculation for quests, I noticed that while playing the game, testing the XP numbers. 

The formula on wowpedia is not quite accurate either, If you check out the earlier versions of my lib, I tried using that formula, but I started to notice a lot of discrepancies in-game.

The current formula should be accurate 99% of the time, but there still might be some wrong data for low level quests.

The only way to make sure, is to watch the XP when rewarded manually, or with a few lines of additional code that compares the values.

Anyways, thanks for the heads up! I'll watch the numbers on my low level characters closely next time I'm leveling.
